#!/bin/bash
#
# ggh -- git-gerrit helper
#
#


show_usage () {
    echo '
ggh - git-gerrit helper

"ggh setup"  - Setup the git aliases listed below in your global git config.  Note, each git alias just calls through to ggh with the arguments passed in.  So ggh could be used directly without the git aliases.

Git Aliases

"git gerrit-clone <url>" ---> git clone <url>, then setup post-commit hook

"git start <local branch> <remote branch>" ---> git checkout -b $1 origin/$2

"git upload" ---> show summary of changes to be uploaded, approve, upload

"git prune" ----> remove all branches not ahead of the remote'

}

cmd_setup () {

    type -P ggh &>/dev/null || { echo "ggh must be in your PATH var in order to be setup." >&2; exit 1; }

    type -P git &>/dev/null || { echo "git must be in your PATH var in order to be setup." >&2; exit 1; }
    

}

cmd_gerrit_clone () {
    echo "fdslj"
}

cmd_start () {
 echo "start"
}

cmd_upload () {
    echo FJDSL
}

cmd_prune () {
    echo fjdskl
}



case "$1" in
    setup)
	cmd_setup
	;;

    gerrit-clone)
	cmd_gerrit_clone $2
	;;

    start)
	cmd_start $2 $3
	;;

    upload)
	cmd_upload
	;;

    prune)
	cmd_prune
	;;

    *)
	show_usage
	;;

esac
